name: CI

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout tutorial-compiler
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorial-compiler
      - name: Checkout playbooks
        uses: actions/checkout@v2
        with:
          repository: devonfw-tutorials/tutorials
          path: playbooks
      - name: echo env
        run: echo ${{ github.event.client_payload.tutorial }}
