name: CI

on:
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: echo env
        run: echo ${{ github.event.client_payload.tutorial }}
